"""added new year columns

Revision ID: 8f74fa23e976
Revises: 96c10ffd610b
Create Date: 2025-12-16 15:05:34.688436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8f74fa23e976'
down_revision: Union[str, Sequence[str], None] = '96c10ffd610b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'user_id',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Integer(),
               nullable=True)
    op.drop_index(op.f('ix_todos_user_id'), table_name='todos')
    op.create_foreign_key(None, 'todos', 'users', ['user_id'], ['id'])
    op.add_column('vegetables', sa.Column('sow_start', sa.Integer(), nullable=True))
    op.add_column('vegetables', sa.Column('sow_end', sa.Integer(), nullable=True))
    op.add_column('vegetables', sa.Column('plant_start', sa.Integer(), nullable=True))
    op.add_column('vegetables', sa.Column('plant_end', sa.Integer(), nullable=True))
    op.add_column('vegetables', sa.Column('harvest_start', sa.Integer(), nullable=True))
    op.add_column('vegetables', sa.Column('harvest_end', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vegetables', 'harvest_end')
    op.drop_column('vegetables', 'harvest_start')
    op.drop_column('vegetables', 'plant_end')
    op.drop_column('vegetables', 'plant_start')
    op.drop_column('vegetables', 'sow_end')
    op.drop_column('vegetables', 'sow_start')
    op.drop_constraint(None, 'todos', type_='foreignkey')
    op.create_index(op.f('ix_todos_user_id'), 'todos', ['user_id'], unique=False)
    op.alter_column('todos', 'user_id',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###
