"""initial tables

Revision ID: 96c10ffd610b
Revises: 
Create Date: 2025-10-24 12:42:19.741656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96c10ffd610b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firebase_uid', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_firebase_uid'), 'users', ['firebase_uid'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('vegetables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('sunlight', sa.String(length=50), nullable=True),
    sa.Column('water', sa.String(length=50), nullable=True),
    sa.Column('soil', sa.String(length=50), nullable=True),
    sa.Column('placements', sa.String(length=50), nullable=True),
    sa.Column('difficulty', sa.String(length=20), nullable=True),
    sa.Column('spacing_down', sa.Integer(), nullable=True),
    sa.Column('spacing_across', sa.Integer(), nullable=True),
    sa.Column('spacing_between', sa.Integer(), nullable=True),
    sa.Column('fertilise', sa.Text(), nullable=True),
    sa.Column('care_1', sa.Text(), nullable=True),
    sa.Column('care_2', sa.Text(), nullable=True),
    sa.Column('care_3', sa.Text(), nullable=True),
    sa.Column('sow', sa.String(length=50), nullable=True),
    sa.Column('plant_hoe', sa.String(length=50), nullable=True),
    sa.Column('harvest', sa.String(length=50), nullable=True),
    sa.Column('harvest_signs', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_vegetables_id'), 'vegetables', ['id'], unique=False)
    op.create_table('user_vegetables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vegetable_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vegetable_id'], ['vegetables.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_vegetables_id'), 'user_vegetables', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_vegetables_id'), table_name='user_vegetables')
    op.drop_table('user_vegetables')
    op.drop_index(op.f('ix_vegetables_id'), table_name='vegetables')
    op.drop_table('vegetables')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_firebase_uid'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
